#----------------------------------------------------------------
# AppVeyor configuration for R packages
#
# REFERENCES:
# * AppVeyor CI: https://ci.appveyor.com/
# * r-travis: https://github.com/craigcitro/r-travis
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .appveyor.yml file at
# https://ci.appveyor.com/tools/validate-yaml 
#----------------------------------------------------------------
environment:
  _R_CHECK_FORCE_SUGGESTS_: false

# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/HenrikBengtsson/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:

 - travis-tool.sh install_bioc affxparser affy AffymetrixDataTestFiles affyPLM aroma.light Biobase BiocGenerics gcrma limma oligo oligoClasses pdInfoBuilder preprocessCore
 - travis-tool.sh install_r aroma.apd aroma.core MASS matrixStats R.cache R.devices R.filesets R.methodsS3 R.oo R.utils
 - travis-tool.sh install_r DBI gsmoothr RColorBrewer

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
